### PR TITLE
add https schema loader

### PR DESCRIPTION
**Pull request by UziTech**
allow json schema to be https

### CODE REVIEW

**Comment by matteobertoldo** [comment]
@bali182 please can u review this change? it's very important because now on every `.dot` files the autocomplete doesn't work. Thanks mate.

**Comment by bali182** [comment]
Hey @UziTech @matteobertoldo sorry for the late answer, I haven't looked much at the notifications. Any of you would be interested in becoming a maintainer of this package as I won't be working on this package? I just cloned & tested it, and a few other serious things are broken (even after applying your https fix - thanks for that btw). So even if I merge your changes it has to be published (by some `apm` command) and it will be still bleeding from many wounds.

Alternatively vscode works great for a lot of json schemas like package.json and tsconfig.json, etc if you are not committed to sticking to atom.

**Comment by UziTech** [comment]
I would be willing to maintain this. I maintain about 50 Atom packages right now, what is one more 😁.

I have tried moving to vscode in the past but it is not configurable enough for me. Atom has some issues but you can change (monkey patch) anything you want.

**Comment by UziTech** [comment]
If you want to we could transfer this package to [atom-ide-community](https://github.com/organizations/atom-ide-community). We have been taking on a lot of abandoned packages lately.

**Comment by matteobertoldo** [comment]
@bali182 I agree with Tony @UziTech ...`atom-ide-community` is the best choice 😊

**Comment by bali182** [comment]
@UziTech I added you as collaborator, if you decide to accept I'll add full write access to the repo 👍

**Comment by UziTech** [comment]
Thank you that is very much appreciated.

**Comment by UziTech** [comment]
@bali182 can you give me full access so I can transfer it to `atom-ide-community`?

**Pull request merged**
